server:
  port: 8080
  servlet:
    session:
      timeout: 30m

application:
  base:
    package: com.egov.template
      
logging:
  level:
    root: INFO
    '[org.springframework]': INFO
    '[com.egov.template]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight([%-3level]) %logger{5} - %msg %n"
    
spring:
  thymeleaf:
    enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      location: C:/workspace/upload
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.220.143.137:15432/anisos
    username: anisos_oper
    password: anisos_oper
    hikari:
      connection-init-sql: SET search_path TO oper
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
    defer-datasource-initialization: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tempUsername
    password: tempPassword
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
        mime:
          charset: UTF-8
        debug: true
      transport:
        protocol: smtp

mybatis:
  mapper-locations: classpath:mappers/sql/**/mapper-*.xml
  type-aliases-package: com.egov.template.services
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    call-setters-on-nulls: true
  