server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
      
spring:
  profiles:
    active:
    #- prod
    - local
      