INSERT INTO CM_TB_AUTH (AUTHRT_CD, AUTHRT_NM, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('ADMIN','관리자','Y', CURRENT_TIMESTAMP,'TEST',NULL,NULL);
INSERT INTO CM_TB_AUTH (AUTHRT_CD, AUTHRT_NM, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('GUEST','게스트','Y', CURRENT_TIMESTAMP,'TEST',NULL,NULL);
INSERT INTO CM_TB_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_SEQ, MENU_URL, MENU_INDCT_YN, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('1000',NULL,'TEST',1,'/test','Y','Y', CURRENT_TIMESTAMP,'TEST',NULL,NULL);
INSERT INTO CM_TB_MENU_AUTH (AUTHRT_CD, MENU_ID, USE_YN, REG_DT, RGTR_ID, MDFCN_DT, MDFR_ID) VALUES
('ADMIN', '1000', 'Y', CURRENT_TIMESTAMP,'TEST',NULL,NULL);
INSERT INTO CM_TB_USER (USER_ID, USER_ENPSWD, USE_YN, REG_DT, RGTR_ID) VALUES
( 'ADMIN', '+O0nKAVk8Of5RcRj5IO4ALHyxtRPbp1ACkSyybrPCvk=', 'Y', CURRENT_TIMESTAMP, 'TEST');
INSERT INTO CM_TB_USER_AUTH (USER_ID, AUTHRT_CD, USE_YN, REG_DT, RGTR_ID) VALUES
('ADMIN', 'ADMIN', 'Y', CURRENT_TIMESTAMP, 'TEST');
